version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: server_postgres
    environment:
      POSTGRES_DB: server_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nelson1234
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Backend_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres


  backend:
    image: backend-app-db
    environment:
      DATABASE_URL: jdbc:postgresql://dpg-cr87qda3esus73frqiv0-a:5432/bankdash_db
      DATABASE_USERNAME: bankdash_db_user
      DATABASE_PASSWORD: yj7ERU34mFzmspqAiJBvnkn6eWFiwamK

volumes:
  postgres_data: