version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Backend_app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres"
      DATABASE_USER: "postgres.mbeuayjarthnctszscco"
      DATABASE_PASSWORD: "2M#fDk!D*Z2H@ap"



