spring:
  application:
    name: Backend

  datasource:
    url: ${SUPABASE_DB_URL}
    username: ${SUPABASE_DB_USER}
    password: ${SUPABASE_DB_PASSWORD}

  flyway:
    enabled: false
    url: ${SUPABASE_DB_URL}
    user: ${SUPABASE_DB_USER}
    password: ${SUPABASE_DB_PASSWORD}
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        connection:
          autocommit: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  devtools:
    restart:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email
            redirect-uri: ${GOOGLE_REDIRECT_URI}

  mail:
    host: smtp.gmail.com
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
          connection timeout: 60000
          timeout: 60000
          write timeout: 60000
        debug: true

  task:
    execution:
      thread-name-prefix: async-email-
      pool:
        core-size: 2
        max-size: 4

logging:
  level:
    org:
      springframework:
        security: DEBUG
        security.oauth2: DEBUG
        web: DEBUG
        filter: DEBUG
    flywaydb:
      DEBUG

application:
  backend:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000

frontend:
  url: ${FRONTEND_URL}

server:
  error:
    include-message: always
  port: 8080

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
