spring:
  application:
    name: Backend

  datasource:
    url: jdbc:postgresql://localhost:5434/server_db
    username: postgres
    password: nelson1234

  flyway:
    enabled: false
    url: jdbc:postgresql://postgres:5432/server_db
    user: postgres
    password: nelson1234
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        connection:
          autocommit: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  devtools:
    restart:
      enabled: true

  mail:
    host: smtp.gmail.com
    port: 465
    username: nelsoncode573@gmail.com
    password: aiai kzto vrhn ntuf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
          connection timeout: 60000
          timeout: 60000
          write timeout: 60000
        debug: true

  task:
    execution:
      thread-name-prefix: async-email-
      pool:
        core-size: 2
        max-size: 4

logging:
  level:
    org:
      springframework:
        security: DEBUG
        security.oauth2: DEBUG
        web: DEBUG
        filter: DEBUG

application:
  backend:
    jwt:
      secret-key: CE5B45053D01A06FCBB9BE55974A1453CDBAF611E571CDC58ECB4A0BDB794682
      expiration: 86400000

frontend:
  url: https://yourfrontend.loca.lt

server:
  error:
    include-message: always
  port: 8080

cloudinary:
  cloud-name: dbjwj3ugv
  api-key: 322279617279884
  api-secret: 65zPc3FpjxzGN5xQpT_AtsrwvZQ

