apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "backend.fullname" . }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  rules:
    - host: {{ index .Values.ingress.hosts 0 "host" | quote }}
      http:
        paths:
          - path: {{ index .Values.ingress.hosts 0 "paths" 0 "path" | quote }}
            pathType: {{ index .Values.ingress.hosts 0 "paths" 0 "pathType" }}
            backend:
              service:
                name: {{ include "backend.fullname" . }}
                port:
                  number: {{ .Values.service.port }}




